default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsbuilder_db

test:
  <<: *default
  database: railsbuilder_db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
